### ISSUE TITLE
Project doesn't compiled as due to command interface file name typo

### ISSUE THREAD

**Issue by Ahmed1monm** [iifawzi/tf-raft#1]
The error 
```
Module '"./interfaces"' has no exported member 'CommandType'.

3 import { CommandType, QueryType, RaftCluster } from "./interfaces";
```
and this happen due to the file name typo as the name is `command.ts` and it imports in the code as `Command.ts` so it needs to fix the import or the file name and it will be better to fix the file name to follow the project naming convention

**Comment by iifawzi** [comment]
Thanks for the fix #2
